---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero
  data_bags_path: test/fixtures/data_bags

platforms:
#  - name: ubuntu-14.04
#  - name: ubuntu-12.04
  - name: centos-7
#  - name: centos-6.7

suites:
  - name: default
    provisioner:
      policyfile: test/fixtures/policies/default.rb
