Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/bionic64"
  # config.vm.box = "centos/7"
   config.vm.box = "bento/centos-7"

  # DOCKER
  # config.vm.network "forwarded_port", guest: 2376, host: 8000
  # config.vm.network "forwarded_port", guest: 2377, host: 8001
  # config.vm.network "forwarded_port", guest: 7946, host: 8002
  # config.vm.network "forwarded_port", guest: 4789, host: 8003

  # haproxy_dockerswarm
  # config.vm.network "forwarded_port", guest: 80, host: 8007
  # config.vm.network "forwarded_port", guest: 443, host: 8008

#  config.vm.network "public_network"
#  config.vm.network "public_network", type: "dhcp", bridge: "eth0"
  config.vm.network "private_network", ip: "192.168.98.108"

  config.vm.synced_folder "/tmp", "/shared/work"

  config.vm.provision "shell", inline: <<-SHELL
  # sudo dpkg -i /shared/install/chef_14.3.37-1_amd64_ubuntu1604.deb
    sudo rpm -Uvh /shared/work/chef-14.6.47-1.el7.x86_64.rpm
    # sudo rpm -Uvh /shared/work/chefdk-3.3.23-1.el7.x86_64.rpm
  SHELL
end

