---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags

verifier:
  name: inspec

platforms:
  - name: bento/centos-7
      
suites:
  - name: default
    run_list:
      - recipe[my_ntp::default]

    attributes:       
      country:
        state:
          city: Sydney
